name: UPLOAD REPORT
on:
 workflow_dispatch:
 push:
  branches:
   - main
jobs: 
  buildJob:
    runs-on: ubuntu-latest 
    steps: 
      - name: Clone the Repo 
        uses: actions/checkout@v5 
      - name: Install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      - name: INstall npm
        run: npm install
      - name: Install dependencies
        run: npm ci 
      - name: Run tests 
        run: npm test
      - name: Debug folder structure
        run:
          pwd
          ls -R
      - name: upload the report to github repo 
        uses: actions/upload-artifact@v4
        with: 
         name: fetch
         path: /home/runner/work/nodejs-sonar-app/nodejs-sonar-app
      - name: Build code 
        run: npm run build s

