name: Upload Reports

on:
  workflow_dispatch:  # This enables the "Run workflow" button
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  buildjob:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repository
      - name: Clone repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cahe: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Upload test report
      - name: Upload test json report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-results/     # CHANGE to your actual test output folder

      # Step 6: Build the app
      - name: Build code
        run: npm run build
