name: WORKFLOW B

on:
  repository_dispatch:
    types: [trigger-file-b]

jobs:
  run_b:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "Workflow B triggered successfully!"
